# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uber' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uber
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'UberTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UberUITests' do
    # Pods for testing
  end

end
